/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package starshoes;

import java.awt.Color;

/**
 *
 * @author Murilo Fernandes
 */
public class FormVendedor extends javax.swing.JFrame {

    /**
     * Creates new form FormVendedor
     */
    
    //Variáveies
    private String tipoFrame;
    
    //Objetos
    Loja starShoes;
    
    public FormVendedor() {
        initComponents();
        starShoes = new Loja();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPessoaFrame = new javax.swing.JInternalFrame();
        addPanel = new javax.swing.JPanel();
        nomeLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        telefoneLabel = new javax.swing.JLabel();
        pessoaisLabel = new javax.swing.JLabel();
        enderecoLabel = new javax.swing.JLabel();
        endLabel = new javax.swing.JLabel();
        compLabel = new javax.swing.JLabel();
        cidadeLabel = new javax.swing.JLabel();
        cepLabel = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        enderecoField = new javax.swing.JTextField();
        compField = new javax.swing.JTextField();
        cidadeField = new javax.swing.JTextField();
        numLabel = new javax.swing.JLabel();
        ufLabel = new javax.swing.JLabel();
        bairroLabel = new javax.swing.JLabel();
        bairroField = new javax.swing.JTextField();
        cadSucess = new javax.swing.JLabel();
        showCod = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        cadastrarBtn = new javax.swing.JButton();
        cpfField = new javax.swing.JFormattedTextField();
        telefoneField = new javax.swing.JFormattedTextField();
        numField = new javax.swing.JFormattedTextField();
        ufField = new javax.swing.JTextField();
        cepField = new javax.swing.JFormattedTextField();
        pesquisarFrame = new javax.swing.JInternalFrame();
        pesquisarPanel = new javax.swing.JPanel();
        procurarLabel = new javax.swing.JLabel();
        codPesLabel = new javax.swing.JLabel();
        codPesField = new javax.swing.JFormattedTextField();
        cpfPesLabel = new javax.swing.JLabel();
        cpfPesField = new javax.swing.JFormattedTextField();
        pesquisarButton = new javax.swing.JButton();
        bairroField1 = new javax.swing.JTextField();
        cpfField1 = new javax.swing.JFormattedTextField();
        telefoneField1 = new javax.swing.JFormattedTextField();
        numField1 = new javax.swing.JFormattedTextField();
        cepField1 = new javax.swing.JFormattedTextField();
        ufField1 = new javax.swing.JTextField();
        endLabel1 = new javax.swing.JLabel();
        compLabel1 = new javax.swing.JLabel();
        cidadeLabel1 = new javax.swing.JLabel();
        cepLabel1 = new javax.swing.JLabel();
        nomeField1 = new javax.swing.JTextField();
        enderecoField1 = new javax.swing.JTextField();
        compField1 = new javax.swing.JTextField();
        cidadeField1 = new javax.swing.JTextField();
        numLabel1 = new javax.swing.JLabel();
        nomeLabel1 = new javax.swing.JLabel();
        cpfLabel1 = new javax.swing.JLabel();
        telefoneLabel1 = new javax.swing.JLabel();
        pessoaisLabel1 = new javax.swing.JLabel();
        enderecoLabel1 = new javax.swing.JLabel();
        ufLabel1 = new javax.swing.JLabel();
        bairroLabel1 = new javax.swing.JLabel();
        transLabel1 = new javax.swing.JLabel();
        transField1 = new javax.swing.JTextField();
        infPesLabel = new javax.swing.JLabel();
        transLabel2 = new javax.swing.JLabel();
        transField2 = new javax.swing.JTextField();
        transLabel3 = new javax.swing.JLabel();
        transField3 = new javax.swing.JTextField();
        addTenisFrame = new javax.swing.JInternalFrame();
        addPanel1 = new javax.swing.JPanel();
        marcaLabel = new javax.swing.JLabel();
        modeloLabel = new javax.swing.JLabel();
        corLabel = new javax.swing.JLabel();
        pessoaisLabel2 = new javax.swing.JLabel();
        pCustoLabel = new javax.swing.JLabel();
        pVendaLabel = new javax.swing.JLabel();
        corField = new javax.swing.JTextField();
        qtdLabel = new javax.swing.JLabel();
        qtdField = new javax.swing.JTextField();
        cadSucess1 = new javax.swing.JLabel();
        showCod1 = new javax.swing.JLabel();
        cancelBtn1 = new javax.swing.JButton();
        cadastrarBtn1 = new javax.swing.JButton();
        marcaField = new javax.swing.JTextField();
        modeloField = new javax.swing.JTextField();
        pCustoField = new javax.swing.JFormattedTextField();
        pVendaField = new javax.swing.JFormattedTextField();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        vendaMenu = new javax.swing.JMenu();
        realizarVenda = new javax.swing.JMenuItem();
        procurarVenda = new javax.swing.JMenuItem();
        clienteMenu = new javax.swing.JMenu();
        adicionarCliente = new javax.swing.JMenuItem();
        procurarCliente = new javax.swing.JMenuItem();
        vendedorMenu = new javax.swing.JMenu();
        adicionarVendedor = new javax.swing.JMenuItem();
        procurarVendedor = new javax.swing.JMenuItem();
        tenisMenu = new javax.swing.JMenu();
        adicionarTenis = new javax.swing.JMenuItem();

        addPessoaFrame.setClosable(true);
        addPessoaFrame.setResizable(true);
        addPessoaFrame.setTitle("Adicionar");
        addPessoaFrame.setMinimumSize(new java.awt.Dimension(82, 24));
        addPessoaFrame.setVisible(true);

        nomeLabel.setText("Nome*:");

        cpfLabel.setText("CPF*:");

        telefoneLabel.setText("Telefone*:");

        pessoaisLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pessoaisLabel.setText("Informações pessoais");

        enderecoLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enderecoLabel.setText("Endereço");

        endLabel.setText("Endereço*:");

        compLabel.setText("Compl.:");

        cidadeLabel.setText("Cidade*:");

        cepLabel.setText("CEP*:");

        nomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFieldActionPerformed(evt);
            }
        });

        numLabel.setText("Nº*:");

        ufLabel.setText("UF*:");

        bairroLabel.setText("Bairro*:");

        cadSucess.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cadSucess.setForeground(new java.awt.Color(0, 102, 0));
        cadSucess.setText("Cliente cadastrado com sucesso.");

        showCod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showCod.setForeground(new java.awt.Color(0, 102, 0));
        showCod.setText("Codigo do cliente: XXXX.");

        cancelBtn.setText("Cancelar");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        cadastrarBtn.setText("Cadastrar");
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        try {
            cpfField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            telefoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        numField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        try {
            cepField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showCod)
                    .addComponent(cadSucess))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(cadastrarBtn)
                .addGap(18, 18, 18)
                .addComponent(cancelBtn)
                .addGap(29, 29, 29))
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(compLabel)
                            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cpfField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPanelLayout.createSequentialGroup()
                                    .addComponent(telefoneLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(telefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPanelLayout.createSequentialGroup()
                                            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(nomeLabel)
                                                .addComponent(cpfLabel))
                                            .addGap(33, 33, 33)
                                            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(addPanelLayout.createSequentialGroup()
                                                    .addComponent(enderecoField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(numLabel))
                                                .addGroup(addPanelLayout.createSequentialGroup()
                                                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPanelLayout.createSequentialGroup()
                                            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                                                    .addComponent(cidadeLabel)
                                                    .addGap(300, 300, 300))
                                                .addGroup(addPanelLayout.createSequentialGroup()
                                                    .addComponent(cepLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addComponent(ufLabel)))
                                    .addGroup(addPanelLayout.createSequentialGroup()
                                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(endLabel)
                                            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(compField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPanelLayout.createSequentialGroup()
                                                    .addComponent(bairroLabel)
                                                    .addGap(32, 32, 32)
                                                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(cidadeField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                                        .addComponent(bairroField)
                                                        .addComponent(cepField)))))
                                        .addGap(56, 56, 56)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(ufField)))))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pessoaisLabel))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enderecoLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(pessoaisLabel)
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel)
                    .addComponent(cpfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneLabel)
                    .addComponent(telefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(enderecoLabel)
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endLabel)
                    .addComponent(enderecoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numLabel)
                    .addComponent(numField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compLabel)
                    .addComponent(compField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairroLabel)
                    .addComponent(bairroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadeLabel)
                    .addComponent(cidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cepLabel)
                    .addComponent(ufLabel)
                    .addComponent(ufField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelBtn)
                            .addComponent(cadastrarBtn))
                        .addGap(24, 24, 24))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(cadSucess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showCod)
                        .addContainerGap())))
        );

        cadSucess.setVisible(false);
        showCod.setVisible(false);

        javax.swing.GroupLayout addPessoaFrameLayout = new javax.swing.GroupLayout(addPessoaFrame.getContentPane());
        addPessoaFrame.getContentPane().setLayout(addPessoaFrameLayout);
        addPessoaFrameLayout.setHorizontalGroup(
            addPessoaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addPessoaFrameLayout.setVerticalGroup(
            addPessoaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pesquisarFrame.setClosable(true);
        pesquisarFrame.setPreferredSize(new java.awt.Dimension(600, 504));
        pesquisarFrame.setVisible(true);

        procurarLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        procurarLabel.setText("Procurar Cliente");

        codPesLabel.setText("Código:");

        codPesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codPesFieldActionPerformed(evt);
            }
        });

        cpfPesLabel.setText("CPF:");

        cpfPesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfPesFieldActionPerformed(evt);
            }
        });

        pesquisarButton.setText("Pesquisar");
        pesquisarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarButtonActionPerformed(evt);
            }
        });

        bairroField1.setEditable(false);

        cpfField1.setEditable(false);
        try {
            cpfField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        telefoneField1.setEditable(false);
        try {
            telefoneField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        numField1.setEditable(false);
        numField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        cepField1.setEditable(false);
        try {
            cepField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        ufField1.setEditable(false);

        endLabel1.setText("Endereço:");

        compLabel1.setText("Compl.:");

        cidadeLabel1.setText("Cidade:");

        cepLabel1.setText("CEP:");

        nomeField1.setEditable(false);
        nomeField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeField1ActionPerformed(evt);
            }
        });

        enderecoField1.setEditable(false);

        compField1.setEditable(false);

        cidadeField1.setEditable(false);

        numLabel1.setText("Nº:");

        nomeLabel1.setText("Nome:");

        cpfLabel1.setText("CPF:");

        telefoneLabel1.setText("Telefone:");

        pessoaisLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pessoaisLabel1.setText("Informações pessoais");

        enderecoLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enderecoLabel1.setText("Endereço");

        ufLabel1.setText("UF:");

        bairroLabel1.setText("Bairro:");

        transLabel1.setText("Total Vendido:");

        transField1.setEditable(false);
        transField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transField1ActionPerformed(evt);
            }
        });

        infPesLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        infPesLabel.setText("Inf. Vendedor");

        transLabel2.setText("Per. Comis.:");

        transField2.setEditable(false);
        transField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transField2ActionPerformed(evt);
            }
        });

        transLabel3.setText("Comissão:");

        transField3.setEditable(false);
        transField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pesquisarPanelLayout = new javax.swing.GroupLayout(pesquisarPanel);
        pesquisarPanel.setLayout(pesquisarPanelLayout);
        pesquisarPanelLayout.setHorizontalGroup(
            pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesquisarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pesquisarPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pesquisarPanelLayout.createSequentialGroup()
                                .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pesquisarPanelLayout.createSequentialGroup()
                                        .addComponent(endLabel1)
                                        .addGap(10, 10, 10)
                                        .addComponent(enderecoField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numLabel1))
                                    .addGroup(pesquisarPanelLayout.createSequentialGroup()
                                        .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bairroLabel1)
                                            .addComponent(compLabel1)
                                            .addComponent(cidadeLabel1)
                                            .addComponent(cepLabel1))
                                        .addGap(22, 22, 22)
                                        .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cepField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cidadeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(compField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bairroField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)
                                        .addComponent(ufLabel1)))
                                .addGap(18, 18, 18)
                                .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ufField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pesquisarPanelLayout.createSequentialGroup()
                                .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pesquisarPanelLayout.createSequentialGroup()
                                        .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nomeLabel1)
                                            .addComponent(cpfLabel1))
                                        .addGap(36, 36, 36)
                                        .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nomeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cpfField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pesquisarPanelLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(telefoneLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(telefoneField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(infPesLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pesquisarPanelLayout.createSequentialGroup()
                                        .addComponent(transLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(transField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pesquisarPanelLayout.createSequentialGroup()
                                        .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(transLabel2)
                                            .addComponent(transLabel3))
                                        .addGap(20, 20, 20)
                                        .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(transField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(transField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addComponent(procurarLabel)
                    .addGroup(pesquisarPanelLayout.createSequentialGroup()
                        .addComponent(codPesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codPesField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(cpfPesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cpfPesField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(pesquisarButton))
                    .addComponent(pessoaisLabel1)
                    .addComponent(enderecoLabel1))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pesquisarPanelLayout.setVerticalGroup(
            pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesquisarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(procurarLabel)
                .addGap(18, 18, 18)
                .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codPesLabel)
                    .addComponent(codPesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfPesLabel)
                    .addComponent(cpfPesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarButton))
                .addGap(26, 26, 26)
                .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pessoaisLabel1)
                    .addComponent(infPesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel1)
                    .addComponent(nomeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transLabel1)
                    .addComponent(transField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpfLabel1)
                    .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cpfField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(transLabel2)
                        .addComponent(transField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneLabel1)
                    .addComponent(telefoneField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transLabel3)
                    .addComponent(transField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(enderecoLabel1)
                .addGap(18, 18, 18)
                .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endLabel1)
                    .addComponent(enderecoField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numLabel1)
                    .addComponent(numField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairroLabel1)
                    .addComponent(bairroField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadeLabel1)
                    .addComponent(cidadeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pesquisarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cepLabel1)
                    .addComponent(ufLabel1)
                    .addComponent(ufField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        transLabel1.setVisible(false);
        transField1.setVisible(false);
        infPesLabel.setVisible(false);
        transLabel2.setVisible(false);
        transField2.setVisible(false);
        transLabel3.setVisible(false);
        transField3.setVisible(false);

        javax.swing.GroupLayout pesquisarFrameLayout = new javax.swing.GroupLayout(pesquisarFrame.getContentPane());
        pesquisarFrame.getContentPane().setLayout(pesquisarFrameLayout);
        pesquisarFrameLayout.setHorizontalGroup(
            pesquisarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pesquisarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pesquisarFrameLayout.setVerticalGroup(
            pesquisarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pesquisarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        addTenisFrame.setClosable(true);
        addTenisFrame.setResizable(true);
        addTenisFrame.setTitle("Adicionar Tênis");
        addTenisFrame.setMinimumSize(new java.awt.Dimension(82, 24));
        addTenisFrame.setVisible(true);

        marcaLabel.setText("Marca:");

        modeloLabel.setText("Modelo:");

        corLabel.setText("Cor:");

        pessoaisLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pessoaisLabel2.setText("Adicionar Tênis");

        pCustoLabel.setText("Preço de custo:");

        pVendaLabel.setText("Preço de venda:");

        corField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corFieldActionPerformed(evt);
            }
        });

        qtdLabel.setText("Quantidade:");

        cadSucess1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cadSucess1.setForeground(new java.awt.Color(0, 102, 0));
        cadSucess1.setText("Tênis cadastrado com sucesso.");

        showCod1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showCod1.setForeground(new java.awt.Color(0, 102, 0));
        showCod1.setText("Codigo do tênis: XXXX.");

        cancelBtn1.setText("Cancelar");
        cancelBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtn1ActionPerformed(evt);
            }
        });

        cadastrarBtn1.setText("Cadastrar");
        cadastrarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtn1ActionPerformed(evt);
            }
        });

        marcaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaFieldActionPerformed(evt);
            }
        });

        modeloField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloFieldActionPerformed(evt);
            }
        });

        pCustoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        pCustoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                calculaPrecoVenda(evt);
            }
        });

        pVendaField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout addPanel1Layout = new javax.swing.GroupLayout(addPanel1);
        addPanel1.setLayout(addPanel1Layout);
        addPanel1Layout.setHorizontalGroup(
            addPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showCod1)
                    .addComponent(cadSucess1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(cadastrarBtn1)
                .addGap(18, 18, 18)
                .addComponent(cancelBtn1)
                .addGap(29, 29, 29))
            .addGroup(addPanel1Layout.createSequentialGroup()
                .addGroup(addPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(addPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(corLabel)
                            .addGroup(addPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(marcaLabel)
                                .addComponent(modeloLabel)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanel1Layout.createSequentialGroup()
                                    .addGroup(addPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pCustoLabel)
                                        .addComponent(pVendaLabel)
                                        .addComponent(qtdLabel))
                                    .addGap(37, 37, 37)
                                    .addGroup(addPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(corField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(marcaField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(modeloField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pCustoField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pVendaField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(qtdField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(addPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pessoaisLabel2)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        addPanel1Layout.setVerticalGroup(
            addPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(pessoaisLabel2)
                .addGap(18, 18, 18)
                .addGroup(addPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addPanel1Layout.createSequentialGroup()
                        .addGroup(addPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marcaLabel)
                            .addComponent(marcaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modeloLabel)
                            .addComponent(modeloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(corLabel)
                            .addComponent(corField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(pCustoLabel))
                    .addComponent(pCustoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pVendaLabel)
                    .addComponent(pVendaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdLabel)
                    .addComponent(qtdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(addPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addPanel1Layout.createSequentialGroup()
                        .addGroup(addPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelBtn1)
                            .addComponent(cadastrarBtn1))
                        .addGap(24, 24, 24))
                    .addGroup(addPanel1Layout.createSequentialGroup()
                        .addComponent(cadSucess1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showCod1)
                        .addContainerGap())))
        );

        cadSucess.setVisible(false);
        showCod.setVisible(false);

        javax.swing.GroupLayout addTenisFrameLayout = new javax.swing.GroupLayout(addTenisFrame.getContentPane());
        addTenisFrame.getContentPane().setLayout(addTenisFrameLayout);
        addTenisFrameLayout.setHorizontalGroup(
            addTenisFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addTenisFrameLayout.setVerticalGroup(
            addTenisFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );

        vendaMenu.setText("Venda");

        realizarVenda.setText("Realizar Venda");
        realizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarVendaActionPerformed(evt);
            }
        });
        vendaMenu.add(realizarVenda);

        procurarVenda.setText("Procurar Venda");
        procurarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurarVendaActionPerformed(evt);
            }
        });
        vendaMenu.add(procurarVenda);

        jMenuBar1.add(vendaMenu);

        clienteMenu.setText("Cliente");

        adicionarCliente.setText("Adicionar Cliente");
        adicionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarClienteActionPerformed(evt);
            }
        });
        clienteMenu.add(adicionarCliente);

        procurarCliente.setText("Procurar Cliente");
        procurarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurarClienteActionPerformed(evt);
            }
        });
        clienteMenu.add(procurarCliente);

        jMenuBar1.add(clienteMenu);

        vendedorMenu.setText("Vendedor");

        adicionarVendedor.setText("Adicionar Vendedor");
        adicionarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarVendedorActionPerformed(evt);
            }
        });
        vendedorMenu.add(adicionarVendedor);

        procurarVendedor.setText("Procurar Vendedor");
        procurarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurarVendedorActionPerformed(evt);
            }
        });
        vendedorMenu.add(procurarVendedor);

        jMenuBar1.add(vendedorMenu);

        tenisMenu.setText("Tênis");

        adicionarTenis.setText("Adicionar Tênis");
        adicionarTenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarTenisActionPerformed(evt);
            }
        });
        tenisMenu.add(adicionarTenis);

        jMenuBar1.add(tenisMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Funções
    public void abrirFrame(javax.swing.JInternalFrame janela) {
        int lDesk = desktopPane.getWidth();
        int aDesk = desktopPane.getHeight();
        janela.setSize(600, 600);
        desktopPane.add(janela);
        janela.setVisible(true);
        janela.setLocation(lDesk/2 - 300, aDesk/2 - 250);
    }
    
    public boolean verificarCadastro() {
        boolean verificado = true;
        
        
        if(nomeField.getText().equals("")) {
            nomeLabel.setForeground(Color.red);
            verificado = false;
        }
        else {
            nomeLabel.setForeground(Color.black);
        }
        
        if(cpfField.getText().equals("   .   .   -  ")) {
            cpfLabel.setForeground(Color.red);
            verificado = false;
        }
        else {
            cpfLabel.setForeground(Color.black);
        }
        
        if(telefoneField.getText().equals("(  )      -    ")) {
            telefoneLabel.setForeground(Color.red);
            verificado = false;
        }
        else {
            telefoneLabel.setForeground(Color.black);
        }
        
        if(enderecoField.getText().equals("")) {
            endLabel.setForeground(Color.red);
            verificado = false;
        }
        else {
            endLabel.setForeground(Color.black);
        }
        
        if(numField.getText().equals("")) {
            numLabel.setForeground(Color.red);
            verificado = false;
        }
        else {
            numLabel.setForeground(Color.black);
        }
        
        if(bairroField.getText().equals("")) {
            bairroLabel.setForeground(Color.red);
            verificado = false;
        }
        else {
            bairroLabel.setForeground(Color.black);
        }
        
        if(cidadeField.getText().equals("")) {
            cidadeLabel.setForeground(Color.red);
            verificado = false;
        }
        else {
            cidadeLabel.setForeground(Color.black);
        }
        
        if(cepField.getText().equals("     -   ")) {
            cepLabel.setForeground(Color.red);
            verificado = false;
        }
        else {
            cepLabel.setForeground(Color.black);
        }
        
        if(ufField.getText().equals("")) {
            ufLabel.setForeground(Color.red);
            verificado = false;
        }
        else {
            ufLabel.setForeground(Color.black);
        }
        
        
        return verificado;
    }
    
    public void limparCadastro() {
        System.out.println("nada");
        nomeField.setText("");
        cpfField.setText("   .   .   -  ");
        telefoneField.setText("(  )      -    ");
        enderecoField.setText("");
        numField.setText("");
        bairroField.setText("");
        cidadeField.setText("");
        cepField.setText("     -   ");
        ufField.setText("");
    }
    
    public void salvarCliente() {
        Cliente cliente = new Cliente();
        cliente.setNome(nomeField.getText());
        cliente.setCpf(cpfField.getText());
        cliente.setTelefone(telefoneField.getText());
        cliente.setEndereco(enderecoField.getText(), Integer.parseInt(numField.getText()), bairroField.getText(), cepField.getText(), 
                cidadeField.getText(), ufField.getText(), compField.getText());
        
        showCod.setText("Codigo do cliente: " + starShoes.adicionarCliente(cliente) + ".");
        showCod.setVisible(true);
        
        cadSucess.setText("Cliente cadastrado com sucesso.");
        cadSucess.setVisible(true);
    }
    
    public void salvarVendedor() {
        Vendedor vendedor = new Vendedor();
        vendedor.setNome(nomeField.getText());
        vendedor.setCpf(cpfField.getText());
        vendedor.setTelefone(telefoneField.getText());
        vendedor.setEndereco(enderecoField.getText(), Integer.parseInt(numField.getText()), bairroField.getText(), cepField.getText(), 
                cidadeField.getText(), ufField.getText(), compField.getText());
        
        showCod.setText("Codigo do vendedor: " + starShoes.adicionarVendedor(vendedor) + ".");
        showCod.setVisible(true);
        
        cadSucess.setText("Vendedor cadastrado com sucesso.");
        cadSucess.setVisible(true);
    }
    
    private void realizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_realizarVendaActionPerformed

    private void procurarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurarVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procurarVendaActionPerformed

    private void adicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarClienteActionPerformed
        tipoFrame = "Cliente";
        addPessoaFrame.setTitle("Adicionar Cliente");
        abrirFrame(addPessoaFrame);
    }//GEN-LAST:event_adicionarClienteActionPerformed
    
    
    
     private void formComponentHidden(java.awt.event.ComponentEvent evt) {                                     
        // TODO add your handling code here:
         System.out.println("Fechou!!!");
    }
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void adicionarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarVendedorActionPerformed
        tipoFrame = "Vendedor";
        addPessoaFrame.setTitle("Adicionar Vendedor");
        abrirFrame(addPessoaFrame);
    }//GEN-LAST:event_adicionarVendedorActionPerformed

    private void nomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFieldActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed

    }//GEN-LAST:event_cancelBtnActionPerformed

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        // TODO add your handling code here:
        if(verificarCadastro()) {
            System.out.println("Verificado");
            if(tipoFrame.equals("Cliente")) {
                salvarCliente();
            }
            else {
                salvarVendedor();
            }
        }
        else {
            System.out.println("Erro");
        }
    }//GEN-LAST:event_cadastrarBtnActionPerformed

    private void procurarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurarClienteActionPerformed
        // TODO add your handling code here:
        tipoFrame = "Cliente";
        
        infPesLabel.setText("Inf. Cliente");
        infPesLabel.setVisible(true);
        
        transLabel1.setText("Débito:");
        transLabel1.setVisible(true);
        transField1.setVisible(true);
        
        transLabel2.setVisible(false);
        transField2.setVisible(false);
        
        transLabel3.setVisible(false);
        transField3.setVisible(false);
        
        abrirFrame(pesquisarFrame);
    }//GEN-LAST:event_procurarClienteActionPerformed

    private void nomeField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeField1ActionPerformed

    private void pesquisarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarButtonActionPerformed
        if(tipoFrame.equals("Cliente")){
            Cliente cliente = starShoes.procurarCliente(Integer.parseInt(codPesField.getText()));
            nomeField1.setText(cliente.getNome());
            cpfField1.setText(cliente.getCpf());
            telefoneField1.setText(cliente.getTelefone());
            enderecoField1.setText(cliente.getEndereco("rua"));
            numField1.setText(cliente.getEndereco("num"));
            compField1.setText(cliente.getEndereco("com"));
            bairroField1.setText(cliente.getEndereco("bai"));
            cidadeField1.setText(cliente.getEndereco("cid"));
            cepField1.setText(cliente.getEndereco("cep"));
            ufField1.setText(cliente.getEndereco("uf"));
            transField1.setText(Float.toString(cliente.getSaldo()));
        }
        else {
            Vendedor vendedor = starShoes.procurarVendedor(Integer.parseInt(codPesField.getText()));
            nomeField1.setText(vendedor.getNome());
            cpfField1.setText(vendedor.getCpf());
            telefoneField1.setText(vendedor.getTelefone());
            enderecoField1.setText(vendedor.getEndereco("rua"));
            numField1.setText(vendedor.getEndereco("num"));
            compField1.setText(vendedor.getEndereco("com"));
            bairroField1.setText(vendedor.getEndereco("bai"));
            cidadeField1.setText(vendedor.getEndereco("cid"));
            cepField1.setText(vendedor.getEndereco("cep"));
            ufField1.setText(vendedor.getEndereco("uf"));
            transField1.setText(Float.toString(vendedor.getValorVendido()));
            transField2.setText(Float.toString(vendedor.getPorcentComissao()));
            transField3.setText(Float.toString(vendedor.calculaComissao()));
        }
    }//GEN-LAST:event_pesquisarButtonActionPerformed

    private void cpfPesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfPesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfPesFieldActionPerformed

    private void codPesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codPesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codPesFieldActionPerformed

    private void transField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transField3ActionPerformed

    private void transField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transField2ActionPerformed

    private void transField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transField1ActionPerformed

    private void procurarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurarVendedorActionPerformed
        // TODO add your handling code here:
        tipoFrame = "Cliente";
        
        infPesLabel.setText("Inf. Vendedor");
        infPesLabel.setVisible(true);
        
        transLabel1.setText("Total Vendido:");
        transLabel1.setVisible(true);
        transField1.setVisible(true);
        
        transLabel2.setText("Per. Comis.:");
        transLabel2.setVisible(true);
        transField2.setVisible(true);
        
        transLabel3.setText("Comissão:");
        transLabel3.setVisible(true);
        transField3.setVisible(true);
        
        abrirFrame(pesquisarFrame);
    }//GEN-LAST:event_procurarVendedorActionPerformed

    private void corFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corFieldActionPerformed

    private void cancelBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtn1ActionPerformed

    private void cadastrarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarBtn1ActionPerformed

    private void marcaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaFieldActionPerformed

    private void modeloFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloFieldActionPerformed

    private void adicionarTenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarTenisActionPerformed
        // TODO add your handling code here:
        abrirFrame(addTenisFrame);
    }//GEN-LAST:event_adicionarTenisActionPerformed

    private void calculaPrecoVenda(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calculaPrecoVenda
        // TODO add your handling code here:
        pVendaField.setText(String.format("%.2f", Float.parseFloat(pCustoField.getText().replace(',', '.')) * 2));
    }//GEN-LAST:event_calculaPrecoVenda
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPanel;
    private javax.swing.JPanel addPanel1;
    private javax.swing.JInternalFrame addPessoaFrame;
    private javax.swing.JInternalFrame addTenisFrame;
    private javax.swing.JMenuItem adicionarCliente;
    private javax.swing.JMenuItem adicionarTenis;
    private javax.swing.JMenuItem adicionarVendedor;
    private javax.swing.JTextField bairroField;
    private javax.swing.JTextField bairroField1;
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JLabel bairroLabel1;
    private javax.swing.JLabel cadSucess;
    private javax.swing.JLabel cadSucess1;
    public javax.swing.JButton cadastrarBtn;
    public javax.swing.JButton cadastrarBtn1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancelBtn1;
    private javax.swing.JFormattedTextField cepField;
    private javax.swing.JFormattedTextField cepField1;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JLabel cepLabel1;
    private javax.swing.JTextField cidadeField;
    private javax.swing.JTextField cidadeField1;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JLabel cidadeLabel1;
    private javax.swing.JMenu clienteMenu;
    private javax.swing.JFormattedTextField codPesField;
    private javax.swing.JLabel codPesLabel;
    private javax.swing.JTextField compField;
    private javax.swing.JTextField compField1;
    private javax.swing.JLabel compLabel;
    private javax.swing.JLabel compLabel1;
    private javax.swing.JTextField corField;
    private javax.swing.JLabel corLabel;
    private javax.swing.JFormattedTextField cpfField;
    private javax.swing.JFormattedTextField cpfField1;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JLabel cpfLabel1;
    private javax.swing.JFormattedTextField cpfPesField;
    private javax.swing.JLabel cpfPesLabel;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel endLabel;
    private javax.swing.JLabel endLabel1;
    private javax.swing.JTextField enderecoField;
    private javax.swing.JTextField enderecoField1;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JLabel enderecoLabel1;
    private javax.swing.JLabel infPesLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField marcaField;
    private javax.swing.JLabel marcaLabel;
    private javax.swing.JTextField modeloField;
    private javax.swing.JLabel modeloLabel;
    private javax.swing.JTextField nomeField;
    private javax.swing.JTextField nomeField1;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JLabel nomeLabel1;
    private javax.swing.JFormattedTextField numField;
    private javax.swing.JFormattedTextField numField1;
    private javax.swing.JLabel numLabel;
    private javax.swing.JLabel numLabel1;
    private javax.swing.JFormattedTextField pCustoField;
    private javax.swing.JLabel pCustoLabel;
    private javax.swing.JFormattedTextField pVendaField;
    private javax.swing.JLabel pVendaLabel;
    private javax.swing.JButton pesquisarButton;
    private javax.swing.JInternalFrame pesquisarFrame;
    private javax.swing.JPanel pesquisarPanel;
    private javax.swing.JLabel pessoaisLabel;
    private javax.swing.JLabel pessoaisLabel1;
    private javax.swing.JLabel pessoaisLabel2;
    private javax.swing.JMenuItem procurarCliente;
    private javax.swing.JLabel procurarLabel;
    private javax.swing.JMenuItem procurarVenda;
    private javax.swing.JMenuItem procurarVendedor;
    private javax.swing.JTextField qtdField;
    private javax.swing.JLabel qtdLabel;
    private javax.swing.JMenuItem realizarVenda;
    private javax.swing.JLabel showCod;
    private javax.swing.JLabel showCod1;
    private javax.swing.JFormattedTextField telefoneField;
    private javax.swing.JFormattedTextField telefoneField1;
    private javax.swing.JLabel telefoneLabel;
    private javax.swing.JLabel telefoneLabel1;
    private javax.swing.JMenu tenisMenu;
    private javax.swing.JTextField transField1;
    private javax.swing.JTextField transField2;
    private javax.swing.JTextField transField3;
    private javax.swing.JLabel transLabel1;
    private javax.swing.JLabel transLabel2;
    private javax.swing.JLabel transLabel3;
    private javax.swing.JTextField ufField;
    private javax.swing.JTextField ufField1;
    private javax.swing.JLabel ufLabel;
    private javax.swing.JLabel ufLabel1;
    private javax.swing.JMenu vendaMenu;
    private javax.swing.JMenu vendedorMenu;
    // End of variables declaration//GEN-END:variables
}
